CREATE TABLE "valorant_players" (
	"id" serial PRIMARY KEY NOT NULL,
	"player" text NOT NULL,
	"agents" text NOT NULL,
	"games" integer NOT NULL,
	"games_won" integer NOT NULL,
	"games_lost" integer NOT NULL,
	"rounds" integer NOT NULL,
	"rounds_won" integer NOT NULL,
	"rounds_lost" integer NOT NULL,
	"acs" real NOT NULL,
	"kd" real NOT NULL,
	"kast_pct" real,
	"adr" real NOT NULL,
	"kills" integer NOT NULL,
	"kpg" real NOT NULL,
	"kpr" real NOT NULL,
	"deaths" integer NOT NULL,
	"dpg" real NOT NULL,
	"dpr" real NOT NULL,
	"assists" integer NOT NULL,
	"apg" real NOT NULL,
	"apr" real NOT NULL,
	"fk" integer NOT NULL,
	"fkpg" real NOT NULL,
	"fd" integer NOT NULL,
	"fdpg" real NOT NULL,
	"hs_pct" real NOT NULL,
	"plants" integer NOT NULL,
	"plants_per_game" real NOT NULL,
	"defuses" integer NOT NULL,
	"defuses_per_game" real NOT NULL,
	"econ_rating" real NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
DROP TABLE "user" CASCADE;